### PR TITLE
Bundle all headers and swift files for multi-crate UniFFI setups

### PR DESCRIPTION
**Pull request by MarcelStruckWO**
In workspaces where UniFFI types are declared in multiple separate crates, UniFFI bindgen generates a set of Swift files, headers and a header map for each Rust crate that declares UniFFI types.
Currently, only the files corresponding to the main crate (from where `cargo swift` was called) are added. This PR copies all the files to the resulting xcode project.

### CODE REVIEW

**Comment by antoniusnaumann** [comment]
Due to #53 being merged, the code for accessing the Swift config should be altered slightly. I think this is how we can do it:


```rust
for output in uniffi_outputs {
        let config = output.bindings.swift;
        let file_name = config.module_name();
        fs::copy(
            out_dir.join(format!("{file_name}.swift")),
            sources.join(format!("{file_name}.swift")),
        )?;

        fs::copy(
            out_dir.join(config.header_filename()),
            headers.join(config.header_filename()),
        )?;
        fs::copy(
            out_dir.join(config.modulemap_filename()),
            headers.join(config.modulemap_filename()),
        )?;
    }
```

Please update the code in bindings.rs accordingly for this PR to be merged.


Thank you for your contribution! :)

**Comment by MarcelStruckWO** [comment]
Unfortunately the `swift` property is crate-private in the `bindings` struct. :/

I guess we could just continue to use the old approach for generating the filenames, just with all the different crate names.

**Comment by MarcelStruckWO** [comment]
> Due to #53 being merged, the code for accessing the Swift config should be altered slightly. I think this is how we can do it:
> 
> ```rust
> for output in uniffi_outputs {
>         let config = output.bindings.swift;
>         let file_name = config.module_name();
>         fs::copy(
>             out_dir.join(format!("{file_name}.swift")),
>             sources.join(format!("{file_name}.swift")),
>         )?;
> 
>         fs::copy(
>             out_dir.join(config.header_filename()),
>             headers.join(config.header_filename()),
>         )?;
>         fs::copy(
>             out_dir.join(config.modulemap_filename()),
>             headers.join(config.modulemap_filename()),
>         )?;
>     }
> ```
> 
> Please update the code in bindings.rs accordingly for this PR to be merged.
> 
> Thank you for your contribution! :)

Unfortunately the `swift` property is crate-private in the `bindings` struct. :/

I guess we could just continue to use the old approach for generating the filenames, just with all the different crate names.

**Comment by antoniusnaumann** [comment]
> > Due to #53 being merged, the code for accessing the Swift config should be altered slightly. I think this is how we can do it:
> > ```rust
> > for output in uniffi_outputs {
> >         let config = output.bindings.swift;
> >         let file_name = config.module_name();
> >         fs::copy(
> >             out_dir.join(format!("{file_name}.swift")),
> >             sources.join(format!("{file_name}.swift")),
> >         )?;
> > 
> >         fs::copy(
> >             out_dir.join(config.header_filename()),
> >             headers.join(config.header_filename()),
> >         )?;
> >         fs::copy(
> >             out_dir.join(config.modulemap_filename()),
> >             headers.join(config.modulemap_filename()),
> >         )?;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please update the code in bindings.rs accordingly for this PR to be merged.
> > Thank you for your contribution! :)
> 
> Unfortunately the `swift` property is crate-private in the `bindings` struct. :/
> 
> I guess we could just continue to use the old approach for generating the filenames, just with all the different crate names.

Ah, you are right. That was an oversight on my side. 

Thanks providing an alternative solution!

**Comment by antoniusnaumann** [comment]
Thank you so much for creating an end-to-end test project for this feature as well. Great contribution!

**Pull request merged**
